// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateToDo(ctx context.Context, arg CreateToDoParams) (Todo, error)
	// ============================================================================
	// USER QUERIES
	// ============================================================================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Soft delete or hard delete scoped to user
	DeleteTodoByID(ctx context.Context, arg DeleteTodoByIDParams) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// ============================================================================
	// TODO QUERIES (Updated with User Scope)
	// ============================================================================
	// Scoped to only list the current user's active todos
	ListToDos(ctx context.Context, userID pgtype.UUID) ([]Todo, error)
	// Ensures users can only fetch their own todos
	ListToDosByID(ctx context.Context, arg ListToDosByIDParams) (Todo, error)
	UpdateToDoPriority(ctx context.Context, arg UpdateToDoPriorityParams) (Todo, error)
	UpdateToDoStatus(ctx context.Context, arg UpdateToDoStatusParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
