// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToDo = `-- name: CreateToDo :one
INSERT INTO todos (
    title,
    description,
    status,
    priority,
    due_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, title, description, status, priority, due_at, completed_at, created_at, updated_at, deleted_at
`

type CreateToDoParams struct {
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      TodoStatus         `json:"status"`
	Priority    TodoPriority       `json:"priority"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) CreateToDo(ctx context.Context, arg CreateToDoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createToDo,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueAt,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTodoByID = `-- name: DeleteTodoByID :exec
DELETE FROM todos WHERE id = $1
`

func (q *Queries) DeleteTodoByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTodoByID, id)
	return err
}

const listToDos = `-- name: ListToDos :many
SELECT id, title, description, status, priority, due_at, completed_at, created_at, updated_at, deleted_at FROM todos
`

func (q *Queries) ListToDos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listToDos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToDosByID = `-- name: ListToDosByID :one
SELECT id, title, description, status, priority, due_at, completed_at, created_at, updated_at, deleted_at FROM todos WHERE id = $1
`

func (q *Queries) ListToDosByID(ctx context.Context, id pgtype.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, listToDosByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateToDoStatus = `-- name: UpdateToDoStatus :one
UPDATE todos
SET 
    status = $2,
    completed_at = CASE WHEN $2 = 'completed'::todo_status THEN CURRENT_TIMESTAMP ELSE NULL END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, description, status, priority, due_at, completed_at, created_at, updated_at, deleted_at
`

type UpdateToDoStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status TodoStatus  `json:"status"`
}

func (q *Queries) UpdateToDoStatus(ctx context.Context, arg UpdateToDoStatusParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateToDoStatus, arg.ID, arg.Status)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
