// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToDo = `-- name: CreateToDo :one
INSERT INTO todos (
    user_id, -- 👈 Added link to the creator
    title,
    description,
    status,
    priority,
    due_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, title, description, status, priority, due_at, completed_at, created_at, updated_at, deleted_at
`

type CreateToDoParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      TodoStatus         `json:"status"`
	Priority    TodoPriority       `json:"priority"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) CreateToDo(ctx context.Context, arg CreateToDoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createToDo,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueAt,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    email,
    password_hash,
    display_name
) VALUES (
    $1, $2, $3
)
RETURNING id, email, password_hash, display_name, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  pgtype.Text `json:"display_name"`
}

// ============================================================================
// USER QUERIES
// ============================================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTodoByID = `-- name: DeleteTodoByID :exec
UPDATE todos 
SET deleted_at = CURRENT_TIMESTAMP 
WHERE id = $1 AND user_id = $2
`

type DeleteTodoByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Soft delete or hard delete scoped to user
func (q *Queries) DeleteTodoByID(ctx context.Context, arg DeleteTodoByIDParams) error {
	_, err := q.db.Exec(ctx, deleteTodoByID, arg.ID, arg.UserID)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, created_at, updated_at, deleted_at FROM users 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listToDos = `-- name: ListToDos :many

SELECT id, user_id, title, description, status, priority, due_at, completed_at, created_at, updated_at, deleted_at FROM todos 
WHERE user_id = $1 AND deleted_at IS NULL
`

// ============================================================================
// TODO QUERIES (Updated with User Scope)
// ============================================================================
// Scoped to only list the current user's active todos
func (q *Queries) ListToDos(ctx context.Context, userID pgtype.UUID) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listToDos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToDosByID = `-- name: ListToDosByID :one
SELECT id, user_id, title, description, status, priority, due_at, completed_at, created_at, updated_at, deleted_at FROM todos 
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type ListToDosByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Ensures users can only fetch their own todos
func (q *Queries) ListToDosByID(ctx context.Context, arg ListToDosByIDParams) (Todo, error) {
	row := q.db.QueryRow(ctx, listToDosByID, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateToDoPriority = `-- name: UpdateToDoPriority :one
UPDATE todos
SET
    priority = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 -- 👈 Security boundary check
RETURNING id, user_id, title, description, status, priority, due_at, completed_at, created_at, updated_at, deleted_at
`

type UpdateToDoPriorityParams struct {
	ID       pgtype.UUID  `json:"id"`
	UserID   pgtype.UUID  `json:"user_id"`
	Priority TodoPriority `json:"priority"`
}

func (q *Queries) UpdateToDoPriority(ctx context.Context, arg UpdateToDoPriorityParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateToDoPriority, arg.ID, arg.UserID, arg.Priority)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateToDoStatus = `-- name: UpdateToDoStatus :one
UPDATE todos
SET 
    status = $3,
    completed_at = CASE WHEN $3 = 'completed'::todo_status THEN CURRENT_TIMESTAMP ELSE NULL END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 -- 👈 Security boundary check
RETURNING id, user_id, title, description, status, priority, due_at, completed_at, created_at, updated_at, deleted_at
`

type UpdateToDoStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Status TodoStatus  `json:"status"`
}

func (q *Queries) UpdateToDoStatus(ctx context.Context, arg UpdateToDoStatusParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateToDoStatus, arg.ID, arg.UserID, arg.Status)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
