// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateToDo(ctx context.Context, arg CreateToDoParams) (Todo, error)
	DeleteTodoByID(ctx context.Context, id pgtype.UUID) error
	ListToDos(ctx context.Context) ([]Todo, error)
	ListToDosByID(ctx context.Context, id pgtype.UUID) (Todo, error)
	UpdateToDoPriority(ctx context.Context, arg UpdateToDoPriorityParams) (Todo, error)
	UpdateToDoStatus(ctx context.Context, arg UpdateToDoStatusParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
